version: '3.8'

services:
  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: chat-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # DynamoDB Local - In-memory (reliable but non-persistent)
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: chat-dynamodb
    ports:
      - "8002:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # DynamoDB Admin UI
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: chat-dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8002
    depends_on:
      dynamodb-local:
        condition: service_healthy

volumes:
  redis_data:
    driver: local