# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from chat import chat_service_pb2 as chat_dot_chat__service__pb2


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateChatroom = channel.unary_unary(
                '/chat.ChatService/CreateChatroom',
                request_serializer=chat_dot_chat__service__pb2.CreateChatroomRequest.SerializeToString,
                response_deserializer=chat_dot_chat__service__pb2.CreateChatroomResponse.FromString,
                _registered_method=True)
        self.JoinChatroom = channel.unary_unary(
                '/chat.ChatService/JoinChatroom',
                request_serializer=chat_dot_chat__service__pb2.JoinChatroomRequest.SerializeToString,
                response_deserializer=chat_dot_chat__service__pb2.JoinChatroomResponse.FromString,
                _registered_method=True)
        self.LeaveChatroom = channel.unary_unary(
                '/chat.ChatService/LeaveChatroom',
                request_serializer=chat_dot_chat__service__pb2.LeaveChatroomRequest.SerializeToString,
                response_deserializer=chat_dot_chat__service__pb2.LeaveChatroomResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/chat.ChatService/SendMessage',
                request_serializer=chat_dot_chat__service__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=chat_dot_chat__service__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.GetMessages = channel.unary_unary(
                '/chat.ChatService/GetMessages',
                request_serializer=chat_dot_chat__service__pb2.GetMessagesRequest.SerializeToString,
                response_deserializer=chat_dot_chat__service__pb2.GetMessagesResponse.FromString,
                _registered_method=True)
        self.GetChatrooms = channel.unary_unary(
                '/chat.ChatService/GetChatrooms',
                request_serializer=chat_dot_chat__service__pb2.GetChatroomsRequest.SerializeToString,
                response_deserializer=chat_dot_chat__service__pb2.GetChatroomsResponse.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateChatroom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinChatroom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveChatroom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatrooms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateChatroom': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChatroom,
                    request_deserializer=chat_dot_chat__service__pb2.CreateChatroomRequest.FromString,
                    response_serializer=chat_dot_chat__service__pb2.CreateChatroomResponse.SerializeToString,
            ),
            'JoinChatroom': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinChatroom,
                    request_deserializer=chat_dot_chat__service__pb2.JoinChatroomRequest.FromString,
                    response_serializer=chat_dot_chat__service__pb2.JoinChatroomResponse.SerializeToString,
            ),
            'LeaveChatroom': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveChatroom,
                    request_deserializer=chat_dot_chat__service__pb2.LeaveChatroomRequest.FromString,
                    response_serializer=chat_dot_chat__service__pb2.LeaveChatroomResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=chat_dot_chat__service__pb2.SendMessageRequest.FromString,
                    response_serializer=chat_dot_chat__service__pb2.SendMessageResponse.SerializeToString,
            ),
            'GetMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=chat_dot_chat__service__pb2.GetMessagesRequest.FromString,
                    response_serializer=chat_dot_chat__service__pb2.GetMessagesResponse.SerializeToString,
            ),
            'GetChatrooms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatrooms,
                    request_deserializer=chat_dot_chat__service__pb2.GetChatroomsRequest.FromString,
                    response_serializer=chat_dot_chat__service__pb2.GetChatroomsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateChatroom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/CreateChatroom',
            chat_dot_chat__service__pb2.CreateChatroomRequest.SerializeToString,
            chat_dot_chat__service__pb2.CreateChatroomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinChatroom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/JoinChatroom',
            chat_dot_chat__service__pb2.JoinChatroomRequest.SerializeToString,
            chat_dot_chat__service__pb2.JoinChatroomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveChatroom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/LeaveChatroom',
            chat_dot_chat__service__pb2.LeaveChatroomRequest.SerializeToString,
            chat_dot_chat__service__pb2.LeaveChatroomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/SendMessage',
            chat_dot_chat__service__pb2.SendMessageRequest.SerializeToString,
            chat_dot_chat__service__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/GetMessages',
            chat_dot_chat__service__pb2.GetMessagesRequest.SerializeToString,
            chat_dot_chat__service__pb2.GetMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatrooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/GetChatrooms',
            chat_dot_chat__service__pb2.GetChatroomsRequest.SerializeToString,
            chat_dot_chat__service__pb2.GetChatroomsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
