// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: stream/stream_service.proto

package stream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_stream_stream_service_proto protoreflect.FileDescriptor

const file_stream_stream_service_proto_rawDesc = "" +
	"\n" +
	"\x1bstream/stream_service.protoByB\x12StreamServiceProtoP\x01Zagithub.com/Saoudyahya/Live-Streaming-Platform-Architecture/services/chat-service/pkg/proto/stream"

var file_stream_stream_service_proto_goTypes = []any{}
var file_stream_stream_service_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stream_stream_service_proto_init() }
func file_stream_stream_service_proto_init() {
	if File_stream_stream_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_stream_service_proto_rawDesc), len(file_stream_stream_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_stream_service_proto_goTypes,
		DependencyIndexes: file_stream_stream_service_proto_depIdxs,
	}.Build()
	File_stream_stream_service_proto = out.File
	file_stream_stream_service_proto_goTypes = nil
	file_stream_stream_service_proto_depIdxs = nil
}
