# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from analytics import analytics_service_pb2 as analytics_dot_analytics__service__pb2


class AnalyticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrackEvent = channel.unary_unary(
                '/analytics.AnalyticsService/TrackEvent',
                request_serializer=analytics_dot_analytics__service__pb2.TrackEventRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__service__pb2.TrackEventResponse.FromString,
                _registered_method=True)
        self.GetUserAnalytics = channel.unary_unary(
                '/analytics.AnalyticsService/GetUserAnalytics',
                request_serializer=analytics_dot_analytics__service__pb2.GetUserAnalyticsRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__service__pb2.GetUserAnalyticsResponse.FromString,
                _registered_method=True)
        self.GetStreamAnalytics = channel.unary_unary(
                '/analytics.AnalyticsService/GetStreamAnalytics',
                request_serializer=analytics_dot_analytics__service__pb2.GetStreamAnalyticsRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__service__pb2.GetStreamAnalyticsResponse.FromString,
                _registered_method=True)
        self.GetRecommendations = channel.unary_unary(
                '/analytics.AnalyticsService/GetRecommendations',
                request_serializer=analytics_dot_analytics__service__pb2.GetRecommendationsRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__service__pb2.GetRecommendationsResponse.FromString,
                _registered_method=True)
        self.GetPlatformMetrics = channel.unary_unary(
                '/analytics.AnalyticsService/GetPlatformMetrics',
                request_serializer=analytics_dot_analytics__service__pb2.GetPlatformMetricsRequest.SerializeToString,
                response_deserializer=analytics_dot_analytics__service__pb2.GetPlatformMetricsResponse.FromString,
                _registered_method=True)


class AnalyticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TrackEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStreamAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlatformMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrackEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackEvent,
                    request_deserializer=analytics_dot_analytics__service__pb2.TrackEventRequest.FromString,
                    response_serializer=analytics_dot_analytics__service__pb2.TrackEventResponse.SerializeToString,
            ),
            'GetUserAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserAnalytics,
                    request_deserializer=analytics_dot_analytics__service__pb2.GetUserAnalyticsRequest.FromString,
                    response_serializer=analytics_dot_analytics__service__pb2.GetUserAnalyticsResponse.SerializeToString,
            ),
            'GetStreamAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStreamAnalytics,
                    request_deserializer=analytics_dot_analytics__service__pb2.GetStreamAnalyticsRequest.FromString,
                    response_serializer=analytics_dot_analytics__service__pb2.GetStreamAnalyticsResponse.SerializeToString,
            ),
            'GetRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendations,
                    request_deserializer=analytics_dot_analytics__service__pb2.GetRecommendationsRequest.FromString,
                    response_serializer=analytics_dot_analytics__service__pb2.GetRecommendationsResponse.SerializeToString,
            ),
            'GetPlatformMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlatformMetrics,
                    request_deserializer=analytics_dot_analytics__service__pb2.GetPlatformMetricsRequest.FromString,
                    response_serializer=analytics_dot_analytics__service__pb2.GetPlatformMetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analytics.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analytics.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TrackEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/TrackEvent',
            analytics_dot_analytics__service__pb2.TrackEventRequest.SerializeToString,
            analytics_dot_analytics__service__pb2.TrackEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetUserAnalytics',
            analytics_dot_analytics__service__pb2.GetUserAnalyticsRequest.SerializeToString,
            analytics_dot_analytics__service__pb2.GetUserAnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStreamAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetStreamAnalytics',
            analytics_dot_analytics__service__pb2.GetStreamAnalyticsRequest.SerializeToString,
            analytics_dot_analytics__service__pb2.GetStreamAnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetRecommendations',
            analytics_dot_analytics__service__pb2.GetRecommendationsRequest.SerializeToString,
            analytics_dot_analytics__service__pb2.GetRecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlatformMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetPlatformMetrics',
            analytics_dot_analytics__service__pb2.GetPlatformMetricsRequest.SerializeToString,
            analytics_dot_analytics__service__pb2.GetPlatformMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
