version: '3.8'

services:
  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: chat-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # DynamoDB Local - Simple in-memory version
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: chat-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"

  # DynamoDB Admin UI (Simple version)
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: chat-dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local

volumes:
  redis_data:
    driver: local