version: '3.8'

services:
  srs-server:
    image: ossrs/srs:5
    container_name: streaming-server-pro
    ports:
      - "1935:1935"    # RTMP
      - "8080:8080"    # HTTP/HLS
      - "1985:1985"    # API
    volumes:
      - ./config/srs.config:/usr/local/srs/conf/srs.conf:ro
      - ./hls:/usr/local/srs/objs/nginx/html/hls:rw
      - ./recordings:/usr/local/srs/objs/nginx/html/recordings:rw
      - ./live:/usr/local/srs/objs/nginx/html/live:rw  # Added live directory
    restart: unless-stopped
    environment:
      - SRS_LOG_TANK=console
      - SRS_LOG_LEVEL=trace
    # Add extra hosts for callback communication
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - streaming-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

networks:
  streaming-network:
    driver: bridge