version: '3.8'

services:
  nginx-rtmp:
    image: alfg/nginx-rtmp
    container_name: streaming-server
    ports:
      - "1935:1935"    # RTMP ingestion port
      - "8080:80"      # HTTP/HLS delivery port
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./hls:/opt/data/hls
      - ./recordings:/opt/data/recordings
      - ./logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - streaming-network

networks:
  streaming-network:
    driver: bridge