version: '3.8'

services:
  srs-optimized:
    image: ossrs/srs:5
    container_name: streaming-server-pro
    ports:
      - "1935:1935"
      - "8080:8080"  
      - "1985:1985"
    volumes:
      - ./config/srs.config:/usr/local/srs/conf/srs.conf:ro
      - ./hls:/usr/local/srs/objs/nginx/html/hls
      - ./recordings:/usr/local/srs/objs/nginx/html/recordings
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_max_syn_backlog=65535